checks:
  javascript: true
  php: true
filter:
  paths:
    - 'resources/js/*'
    - 'src/*'
  dependency_paths:
    - 'vendor/*'

build:
  image: default-jammy
  environment:
    node: v18
  nodes:
    analysis:
      environment:
        node: v18
        php:
          version: 8.2
          pecl_extensions:
            - zip
      tests:
        override:
          - js-scrutinizer-run
          - php-scrutinizer-run
