checks:
  php: true
filter:
  paths:
    - 'src/*'
  dependency_paths:
    - 'vendor/*'

# new PHP Analysis
build:
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
