sudo: false

language: php

before_install:
  # Use GitHub OAuth token with Composer to increase API limits.
  - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi

install:
  # Install Composer dependencies.
  - composer install --prefer-dist --no-interaction

script:
  # Run PHPUnit with coverage.
  - vendor/bin/phpunit --coverage-clover=clover.xml

after_success:
  # Upload coverage report to CodeCov.io
  - bash <(curl -s https://codecov.io/bash)

jobs:
  fast_finish: true

  include:
    - php: 7.1
    - php: 7.2
    - php: 7.2
      env: "RUN=phpcs"
      script: |
        vendor/bin/phpcs -n -p --extensions=php \
          --standard=vendor/cakephp/cakephp-codesniffer/CakePHP --ignore=/Migrations/,/Seeds/ \
          ./config ./src ./tests ./plugins/*/*/config ./plugins/*/*/src ./plugins/*/*/tests
      after_success: skip
